# Generated by Django 2.2.26 on 2022-08-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(help_text='url', max_length=2000)),
                ('artist', models.TextField(help_text='artist', max_length=1000)),
                ('album', models.TextField(help_text='album', max_length=1000)),
                ('title', models.TextField(help_text='title', max_length=1000)),
                ('category', models.TextField(help_text='category', max_length=1000)),
                ('subcategory', models.TextField(help_text='subcategory', max_length=1000)),
                ('tag', models.TextField(help_text='tag', max_length=1000)),
                ('date_saved', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['artist', 'album', 'title'],
            },
        ),
    ]
